In [235]:
import pandas as pd
data = pd.read_csv('taxi_trip_pricing.csv')
df = pd.DataFrame(data)
df.iloc[0:26]

,Trip_Distance_km,Time_of_Day,Day_of_Week,Passenger_Count,Traffic_Conditions,Weather,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
0,19.35000,Morning,Weekday,3.0,Low,Clear,3.56,0.80,0.32,53.82,36.262400
1,47.59000,Afternoon,Weekday,1.0,High,Clear,NaN,0.62,0.43,40.57,NaN
2,36.87000,Evening,Weekend,1.0,High,Clear,2.70,1.21,0.15,37.27,52.903200
3,30.33000,Evening,Weekday,4.0,Low,NaN,3.48,0.51,0.15,116.81,36.469800
4,NaN,Evening,Weekday,3.0,High,Clear,2.93,0.63,0.32,22.64,15.618000
5,8.64000,Afternoon,Weekend,2.0,Medium,Clear,2.55,1.71,0.48,89.33,60.202800
6,3.85000,Afternoon,Weekday,4.0,High,Rain,3.51,1.66,NaN,5.05,11.264500
7,43.44000,Evening,Weekend,3.0,NaN,Clear,2.97,1.87,0.23,NaN,101.121600
8,30.45000,Morning,Weekday,3.0,High,Clear,2.77,1.78,0.34,110.33,NaN
9,35.70000,Afternoon,Weekday,2.0,Low,Rain,3.39,1.52,0.47,NaN,75.565700
10,NaN,Morning,Weekday,4.0,NaN,Clear,2.40,0.58,0.43,26.34,14.892000
11,48.53000,Night,Weekday,3.0,Low,Clear,4.78,NaN,0.50,79.94,NaN
12,41.79000,Night,Weekend,3.0,High,Clear,4.60,1.77,0.11,86.95,88.132800
13,11.40000,Morning,Weekday,3.0,NaN,Clear,4.12,NaN,0.15,84.12,36.118000
14,9.91000,Evening,Weekday,2.0,High,Clear,2.32,1.26,0.34,41.72,28.991400
15,9.99000,Night,Weekday,4.0,High,Clear,4.33,0.85,0.43,34.00,27.441500
16,15.91000,Morning,Weekday,4.0,Low,Clear,4.42,1.77,0.21,114.93,56.716000
17,26.71000,Afternoon,Weekend,4.0,Low,Rain,4.30,1.59,0.20,111.18,69.004900
18,22.17000,Night,NaN,4.0,Low,Clear,2.34,1.97,0.41,57.59,69.626800
19,15.27000,Morning,NaN,NaN,Low,Clear,3.93,0.73,0.12,NaN,27.354300
20,30.98000,Afternoon,Weekend,1.0,Low,Rain,4.50,0.84,0.25,57.02,44.778200
21,7.84000,Morning,Weekday,4.0,Medium,NaN,3.73,0.82,0.30,53.80,26.298800
22,105.94355,Night,Weekend,2.0,Low,Rain,3.94,1.69,0.32,23.03,201.869509
23,18.95000,Night,Weekday,1.0,Low,Clear,3.38,0.78,0.39,54.04,39.236600
24,23.35000,Night,NaN,3.0,Low,Rain,3.59,0.60,0.24,66.80,33.632000
25,39.47000,Afternoon,Weekday,1.0,Low,Clear,NaN,NaN,0.35,7.59,83.696500

In [236]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Trip_Distance_km       950 non-null    float64
 1   Time_of_Day            950 non-null    str
 2   Day_of_Week            950 non-null    str
 3   Passenger_Count        950 non-null    float64
 4   Traffic_Conditions     950 non-null    str
 5   Weather                950 non-null    str
 6   Base_Fare              950 non-null    float64
 7   Per_Km_Rate            950 non-null    float64
 8   Per_Minute_Rate        950 non-null    float64
 9   Trip_Duration_Minutes  950 non-null    float64
 10  Trip_Price             951 non-null    float64
dtypes: float64(7), str(4)
memory usage: 86.1 KB

In [237]:
df.isna().sum()

Trip_Distance_km         50
Time_of_Day              50
Day_of_Week              50
Passenger_Count          50
Traffic_Conditions       50
Weather                  50
Base_Fare                50
Per_Km_Rate              50
Per_Minute_Rate          50
Trip_Duration_Minutes    50
Trip_Price               49
dtype: int64

In [238]:
for col in df.columns:
    if df[col].dtype in ['int64', 'float32']:
        df[col] = df[col].fillna(df[col].mean(),inplace=True)
    else:
        df[col] = df[col].fillna(df[col].mode()[0], inplace=True)

C:\Users\jyothi.s\AppData\Local\Temp\ipykernel_26972\2631667849.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col] = df[col].fillna(df[col].mode()[0], inplace=True)

In [239]:
df.isnull().sum()

Trip_Distance_km         0
Time_of_Day              0
Day_of_Week              0
Passenger_Count          0
Traffic_Conditions       0
Weather                  0
Base_Fare                0
Per_Km_Rate              0
Per_Minute_Rate          0
Trip_Duration_Minutes    0
Trip_Price               0
dtype: int64

In [240]:
df.duplicated().sum()

np.int64(0)

In [241]:
df.dtypes

Trip_Distance_km         float64
Time_of_Day                  str
Day_of_Week                  str
Passenger_Count          float64
Traffic_Conditions           str
Weather                      str
Base_Fare                float64
Per_Km_Rate              float64
Per_Minute_Rate          float64
Trip_Duration_Minutes    float64
Trip_Price               float64
dtype: object

In [242]:
df.shape

(1000, 11)

In [243]:
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]

In [244]:
df.shape

(974, 11)

In [245]:

df.isnull().sum()

Trip_Distance_km         0
Time_of_Day              0
Day_of_Week              0
Passenger_Count          0
Traffic_Conditions       0
Weather                  0
Base_Fare                0
Per_Km_Rate              0
Per_Minute_Rate          0
Trip_Duration_Minutes    0
Trip_Price               0
dtype: int64

In [246]:
df.iloc[27:45]

,Trip_Distance_km,Time_of_Day,Day_of_Week,Passenger_Count,Traffic_Conditions,Weather,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
29,3.28,Evening,Weekday,2.0,Medium,Clear,2.88,1.76,0.20,78.04,24.2608
30,30.77,Morning,Weekday,1.0,Low,Clear,3.64,1.33,0.13,109.60,58.8121
31,9.36,Afternoon,Weekday,1.0,Medium,Clear,2.40,1.85,0.15,7.07,20.7765
32,4.19,Morning,Weekday,1.0,Low,Clear,4.07,1.89,0.19,69.06,6.1269
33,47.50,Morning,Weekend,3.0,Low,Clear,4.39,0.51,0.30,95.55,57.2800
34,48.32,Morning,Weekday,2.0,Low,Clear,2.49,0.61,0.44,67.25,61.5552
35,40.61,Afternoon,Weekday,1.0,Low,Clear,2.31,0.88,0.38,42.25,54.1018
36,15.93,Afternoon,Weekday,2.0,Low,Clear,2.44,1.50,0.42,20.67,35.0164
37,5.79,Evening,Weekday,4.0,Low,Clear,4.63,1.83,0.24,107.07,40.9225
38,34.53,Morning,Weekday,3.0,Medium,Clear,3.58,0.63,0.26,59.14,60.0471
39,22.57,Afternoon,Weekday,1.0,Low,Clear,3.40,1.41,0.15,105.98,62.7785
40,6.98,Afternoon,Weekend,2.0,Low,Clear,2.32,0.78,0.18,72.37,20.7910
41,25.26,Evening,Weekday,2.0,High,Clear,3.95,1.71,0.12,82.53,57.0482
42,2.69,Afternoon,Weekday,4.0,Low,Clear,4.60,1.95,0.34,97.49,42.9921
43,45.56,Afternoon,Weekday,3.0,Low,Clear,3.94,0.90,0.50,80.80,85.8840
44,13.68,Evening,Weekend,3.0,High,Clear,3.88,0.63,0.17,50.78,29.4758
45,33.46,Afternoon,Weekend,2.0,Low,Rain,2.23,0.63,0.12,64.07,30.9982
46,16.27,Morning,Weekday,1.0,Low,Clear,2.34,0.63,0.41,97.35,64.0553

In [247]:
df = df.reset_index(drop=True)

In [248]:
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder
ohe = OneHotEncoder(sparse_output=False, drop='first')

oe = OrdinalEncoder()

ohe_data =  ohe.fit_transform(df[['Time_of_Day', 'Weather', 'Day_of_Week']])
ohe_df = pd.DataFrame(ohe_data, columns=ohe.get_feature_names_out(['Time_of_Day', 'Weather', 'Day_of_Week']))
df = pd.concat([df.drop(['Time_of_Day', 'Weather', 'Day_of_Week'], axis=1), ohe_df], axis=1)
df.iloc[27:45]

,Trip_Distance_km,Passenger_Count,Traffic_Conditions,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price,Time_of_Day_Evening,Time_of_Day_Morning,Time_of_Day_Night,Weather_Rain,Weather_Snow,Day_of_Week_Weekend
27,3.28,2.0,Medium,2.88,1.76,0.20,78.04,24.2608,1.0,0.0,0.0,0.0,0.0,0.0
28,30.77,1.0,Low,3.64,1.33,0.13,109.60,58.8121,0.0,1.0,0.0,0.0,0.0,0.0
29,9.36,1.0,Medium,2.40,1.85,0.15,7.07,20.7765,0.0,0.0,0.0,0.0,0.0,0.0
30,4.19,1.0,Low,4.07,1.89,0.19,69.06,6.1269,0.0,1.0,0.0,0.0,0.0,0.0
31,47.50,3.0,Low,4.39,0.51,0.30,95.55,57.2800,0.0,1.0,0.0,0.0,0.0,1.0
32,48.32,2.0,Low,2.49,0.61,0.44,67.25,61.5552,0.0,1.0,0.0,0.0,0.0,0.0
33,40.61,1.0,Low,2.31,0.88,0.38,42.25,54.1018,0.0,0.0,0.0,0.0,0.0,0.0
34,15.93,2.0,Low,2.44,1.50,0.42,20.67,35.0164,0.0,0.0,0.0,0.0,0.0,0.0
35,5.79,4.0,Low,4.63,1.83,0.24,107.07,40.9225,1.0,0.0,0.0,0.0,0.0,0.0
36,34.53,3.0,Medium,3.58,0.63,0.26,59.14,60.0471,0.0,1.0,0.0,0.0,0.0,0.0
37,22.57,1.0,Low,3.40,1.41,0.15,105.98,62.7785,0.0,0.0,0.0,0.0,0.0,0.0
38,6.98,2.0,Low,2.32,0.78,0.18,72.37,20.7910,0.0,0.0,0.0,0.0,0.0,1.0
39,25.26,2.0,High,3.95,1.71,0.12,82.53,57.0482,1.0,0.0,0.0,0.0,0.0,0.0
40,2.69,4.0,Low,4.60,1.95,0.34,97.49,42.9921,0.0,0.0,0.0,0.0,0.0,0.0
41,45.56,3.0,Low,3.94,0.90,0.50,80.80,85.8840,0.0,0.0,0.0,0.0,0.0,0.0
42,13.68,3.0,High,3.88,0.63,0.17,50.78,29.4758,1.0,0.0,0.0,0.0,0.0,1.0
43,33.46,2.0,Low,2.23,0.63,0.12,64.07,30.9982,0.0,0.0,0.0,1.0,0.0,1.0
44,16.27,1.0,Low,2.34,0.63,0.41,97.35,64.0553,0.0,1.0,0.0,0.0,0.0,0.0

In [249]:
oe_data = oe.fit_transform(df[['Traffic_Conditions']])
oe_df = pd.DataFrame(oe_data, columns=oe.get_feature_names_out(['Traffic_Conditions']))
df = pd.concat([df.drop(['Traffic_Conditions'], axis=1), oe_df], axis=1)
df.iloc[27:45]

,Trip_Distance_km,Passenger_Count,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price,Time_of_Day_Evening,Time_of_Day_Morning,Time_of_Day_Night,Weather_Rain,Weather_Snow,Day_of_Week_Weekend,Traffic_Conditions
27,3.28,2.0,2.88,1.76,0.20,78.04,24.2608,1.0,0.0,0.0,0.0,0.0,0.0,2.0
28,30.77,1.0,3.64,1.33,0.13,109.60,58.8121,0.0,1.0,0.0,0.0,0.0,0.0,1.0
29,9.36,1.0,2.40,1.85,0.15,7.07,20.7765,0.0,0.0,0.0,0.0,0.0,0.0,2.0
30,4.19,1.0,4.07,1.89,0.19,69.06,6.1269,0.0,1.0,0.0,0.0,0.0,0.0,1.0
31,47.50,3.0,4.39,0.51,0.30,95.55,57.2800,0.0,1.0,0.0,0.0,0.0,1.0,1.0
32,48.32,2.0,2.49,0.61,0.44,67.25,61.5552,0.0,1.0,0.0,0.0,0.0,0.0,1.0
33,40.61,1.0,2.31,0.88,0.38,42.25,54.1018,0.0,0.0,0.0,0.0,0.0,0.0,1.0
34,15.93,2.0,2.44,1.50,0.42,20.67,35.0164,0.0,0.0,0.0,0.0,0.0,0.0,1.0
35,5.79,4.0,4.63,1.83,0.24,107.07,40.9225,1.0,0.0,0.0,0.0,0.0,0.0,1.0
36,34.53,3.0,3.58,0.63,0.26,59.14,60.0471,0.0,1.0,0.0,0.0,0.0,0.0,2.0
37,22.57,1.0,3.40,1.41,0.15,105.98,62.7785,0.0,0.0,0.0,0.0,0.0,0.0,1.0
38,6.98,2.0,2.32,0.78,0.18,72.37,20.7910,0.0,0.0,0.0,0.0,0.0,1.0,1.0
39,25.26,2.0,3.95,1.71,0.12,82.53,57.0482,1.0,0.0,0.0,0.0,0.0,0.0,0.0
40,2.69,4.0,4.60,1.95,0.34,97.49,42.9921,0.0,0.0,0.0,0.0,0.0,0.0,1.0
41,45.56,3.0,3.94,0.90,0.50,80.80,85.8840,0.0,0.0,0.0,0.0,0.0,0.0,1.0
42,13.68,3.0,3.88,0.63,0.17,50.78,29.4758,1.0,0.0,0.0,0.0,0.0,1.0,0.0
43,33.46,2.0,2.23,0.63,0.12,64.07,30.9982,0.0,0.0,0.0,1.0,0.0,1.0,1.0
44,16.27,1.0,2.34,0.63,0.41,97.35,64.0553,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [250]:
df.isna().sum()

Trip_Distance_km         0
Passenger_Count          0
Base_Fare                0
Per_Km_Rate              0
Per_Minute_Rate          0
Trip_Duration_Minutes    0
Trip_Price               0
Time_of_Day_Evening      0
Time_of_Day_Morning      0
Time_of_Day_Night        0
Weather_Rain             0
Weather_Snow             0
Day_of_Week_Weekend      0
Traffic_Conditions       0
dtype: int64

In [251]:
print(df.index)

RangeIndex(start=0, stop=974, step=1)

In [252]:
df.dtypes

Trip_Distance_km         float64
Passenger_Count          float64
Base_Fare                float64
Per_Km_Rate              float64
Per_Minute_Rate          float64
Trip_Duration_Minutes    float64
Trip_Price               float64
Time_of_Day_Evening      float64
Time_of_Day_Morning      float64
Time_of_Day_Night        float64
Weather_Rain             float64
Weather_Snow             float64
Day_of_Week_Weekend      float64
Traffic_Conditions       float64
dtype: object

In [253]:
correlation = df.corr()['Trip_Price']
correlation.sort_values(ascending=False)

Trip_Price               1.000000
Trip_Distance_km         0.573185
Per_Km_Rate              0.343118
Trip_Duration_Minutes    0.297477
Per_Minute_Rate          0.238290
Passenger_Count          0.044811
Time_of_Day_Evening      0.034548
Base_Fare                0.026638
Weather_Rain             0.020274
Weather_Snow             0.014933
Day_of_Week_Weekend      0.006913
Time_of_Day_Night        0.000916
Traffic_Conditions      -0.022465
Time_of_Day_Morning     -0.027217
Name: Trip_Price, dtype: float64

In [254]:
from sklearn.model_selection import train_test_split
X = df.drop('Trip_Price', axis=1)
y = df['Trip_Price']

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [255]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [256]:
from sklearn.linear_model import LinearRegression
lr_model = LinearRegression()
lr_model.fit(x_train_scaled, y_train)
lr_y_pred = lr_model.predict(x_test_scaled)

In [257]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

print("MAE:", mean_absolute_error(y_test, lr_y_pred))
print("MSE:", mean_squared_error(y_test, lr_y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, lr_y_pred)))
print("R2 Score:", r2_score(y_test, lr_y_pred))

MAE: 8.35939332041286
MSE: 141.3622211117745
RMSE: 11.889584564305622
R2 Score: 0.7226460027139625

In [266]:
train_r2 = lr_model.score(x_train_scaled, y_train)

print("Train R2:", train_r2)

test_r2 = lr_model.score(x_test_scaled, y_test)

print("Test R2:", test_r2)

Train R2: 0.6068329995920392
Test R2: 0.7226460027139625

In [ ]:
from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor(random_state=42)


dt.fit(x_train, y_train)

y_pred_dt = dt.predict(x_test)

print("MAE:", mean_absolute_error(y_test, y_pred_dt))
print("MSE:", mean_squared_error(y_test, y_pred_dt))        
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_dt)))
print("R2 Score:", r2_score(y_test, y_pred_dt))

MAE: 12.703729230769227
MSE: 363.15198666707687
RMSE: 19.05654708143836
R2 Score: 0.28749241252484736

In [265]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

rf.fit(x_train, y_train)

y_pred_rf = rf.predict(x_test)


print("MAE:", mean_absolute_error(y_test,y_pred_rf))
print("MSE:", mean_squared_error(y_test, y_pred_rf))        
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_rf)))
print("R2 Score:", r2_score(y_test, y_pred_rf))

MAE: 7.592387943589738
MSE: 113.58063101928873
RMSE: 10.657421405728908
R2 Score: 0.7771537417867699